config/routes.rb
Rails.application.routes.draw do
root 'metros#index'
  resources :metros do
    resources :instructors
  end

  resources :instructors do
    resources :observations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  belongs_to :metro
  has_many :observations, dependent: :destroy
end

app/models/metro.rb
class Metro < ApplicationRecord
  has_many :instructors, dependent: :destroy
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :instructor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def new
    @metro = Metro.find(params[:metro_id])
    @instructor = Instructor.new
  end

  def create
    @metro = Metro.find(params[:metro_id])
    @instructor = @metro.instructors.create!(instructor_params)
    redirect_to @metro
  end

  def show
    @instructor = Instructor.find(params[:id])
    @metro = @instructor.metro
  end

  def edit
    @instructor = Instructor.find(params[:id])
    @metro = @instructor.metro
  end

  def update
    @instructor = Instructor.find(params[:id])
    if @instructor.update(instructor_params)
      flash[:notice] = "#{@instructor.name} was successfully updated."
      redirect_to @instructor
    else
      render :edit
    end
  end

  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy
    redirect_to @instructor.house
  end

  private
  def instructor_params
    params.require(:instructor).permit(:name)
  end
end

app/controllers/metros_controller.rb
class MetrosController < ApplicationController
  def index
    @metros = Metro.all
  end

  def show
    @metro = Metro.find(params[:id])
  end
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController

  def new
    @instructor = Instructor.find(params[:instructor_id])
    @observation = Observation.new
  end

  def create
    @instructor = Instructor.find(params[:instructor_id])
    @observation = @instructor.observations.create!(observation_params)
    redirect_to @instructor
  end

  def edit
    @observation = Observation.find(params[:id])
    @instructor = @observation.instructor
  end

  def update
    @instructor = Instructor.find(params[:instructor_id])
    @observation = Observation.find(params[:id])
    if @observation.update(observation_params)
      flash[:notice] = "Observation was successfully updated."
      redirect_to @instructor
    else
      render :edit
    end
  end

  def destroy
    @observation = Observation.find(params[:id])
    @observation.destroy
    redirect_to @observation.instructor
  end

  private
  def observation_params
    params.require(:observation).permit(:instance, :obs_date, :created_by, :obs_notes, :prep, :framing, :inst, :cfu, :active, :obs_edit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/instructors/show.html.erb
<h2><%= link_to "Metros", metros_path %></h2>

<h2><%= @instructor.name %></h2>
<h3><%= @metro.name %></h3>

<h3>Observations <%= link_to "(+)", new_instructor_observation_path(@instructor) %></h3>

<% @instructor.observations.each do |observation| %>
  <p>Course:<%= observation.instance %> </p>
  <p>Created By: <%= observation.created_by %> </p>
  <p>Date: <%= observation.obs_date %> </p>
  <p>Notes: <%= observation.obs_notes %> </p>
  <p>Prep: <%= observation.prep %> </p>
  <p>Framing: <%= observation.framing %> </p>
  <p>Instruction: <%= observation.inst %> </p>
  <p>CFU: <%= observation.cfu %> </p>
  <p>Active Learning: <%= observation.active %> </p>
  <p>Date Edited: <%= observation.obs_edit %> </p>
  <p><%= link_to "(edit)", edit_instructor_observation_path(@instructor, observation) %></p>
  <p><%= link_to 'Delete', instructor_observation_path(@instructor, observation),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ObsTool</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/metros/index.html.erb
<h2><%= link_to "Metros", metros_path %></h2>

  <% @metros.each do |metro| %>
      <h3><%= link_to metro.name, metro_path(metro) %>
  <% end %>

app/views/metros/show.html.erb
<h2><%= link_to "Metros", metros_path %></h2>
<h3><%= @metro.name %></h3>

<% @metro.instructors.each do |instructor| %>
    <p><%= link_to instructor.name, metro_instructor_path(@metro, instructor) %>  <%= link_to "(edit)", edit_metro_instructor_path(@metro, instructor) %></p>
<% end %>

app/views/observations/_form.html.erb
<%= form_for([@instructor, @observation]) do |f| %>

  <%= f.label :instance %>
  <%= f.text_field :instance %>
  <%= f.label :created_by %>
  <%= f.text_field :created_by %>
  <%= f.label :obs_notes %>
  <%= f.text_field :obs_notes %>
  <%= f.label :prep %>
  <%= f.text_field :prep %>
  <%= f.label :framing %>
  <%= f.text_field :framing %>
  <%= f.label :inst %>
  <%= f.text_field :inst %>
  <%= f.label :cfu %>
  <%= f.text_field :cfu %>
  <%= f.label :active %>
  <%= f.text_field :active %>
  <%= f.submit %>

<% end %>

app/views/observations/edit.html.erb
<h2>Edit Observation</h2>

<%= render 'form' %>

<%= link_to 'Delete!', instructor_observation_path(@instructor, @observation), method: :delete, class: 'delete' %>

app/views/observations/new.html.erb
<h2>New Observation</h2>

<%= render 'form' %>